before_script:
- bash ci/docker_install.sh > /dev/null

test:5.6:
  image: php:5.6-cli
  script:
  - composer install
  - phpunit --configuration phpunit.xml

test:7.0:
  image: php:7.0-cli
  script:
  - composer install
  - phpunit --configuration phpunit.xml
