before_script:
- apk add --no-cache bash &> /dev/null
- bash ci/docker_install.sh &> /dev/null

test:5.6:
  image: php:5.6-alpine
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

test:7.0:
  image: php:7.0-alpine
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

coverage:
  image: php:7.0-alpine
  script:
  - composer install &> /dev/null
  - phpunit --coverage-text --colors=never --configuration phpunit.xml

pages:
  image: php:7.0-alpine
  script:
  - composer install &> /dev/null
  - bin/generate-docs
  artifacts:
    paths:
    - docs
  only:
  - develop
