test:5.6:
  image: 1of0/php-ci:5.6
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

test:7.0:
  image: 1of0/php-ci:7.0
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

coverage:
  image: 1of0/php-ci:7.0
  script:
  - composer install &> /dev/null
  - phpunit --coverage-text --colors=never --configuration phpunit.xml

pages:
  image: 1of0/php-ci:7.0
  script:
  - composer install &> /dev/null
  - bin/generate-docs
  - mv docs public
  artifacts:
    paths:
    - public
  only:
  - develop
