before_script:
- apk add --no-cache bash
- bash ci/docker_install.sh

test:5.6:
  image: php:5.6-alpine
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

test:7.0:
  image: php:7.0-alpine
  script:
  - composer install &> /dev/null
  - phpunit --configuration phpunit.xml

coverage:
  image: php:7.0-alpine
  script:
  - composer install &> /dev/null
  - phpunit --coverage-text --colors=never --configuration phpunit.xml
